# base image
from python:3.7.2-alpine

# install dependencies
run apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
workdir /usr/src/app

# add and install requirements
copy ./requirements.txt /usr/src/app/requirements.txt
run pip install -r requirements.txt

# add entrypoint.sh
copy ./entrypoint-prod.sh /usr/src/app/entrypoint.sh
run chmod +x /usr/src/app/entrypoint.sh

# add app
copy . /usr/src/app

# run server
cmd ["/usr/src/app/entrypoint.sh"]
