# base image
from python:3.7.2-alpine

# install dependencies
run apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
workdir /app/users

# add app
copy . /app/users

# add and install requirements
run pip install --trusted-host pypi.python.org -r requirements.txt

# add entrypoint.sh
copy ./entrypoint.sh /app/users/entrypoint.sh
run chmod +x /app/users/entrypoint.sh

# run server
cmd ["/app/users/entrypoint.sh"]
